apiVersion: v1
kind: PersistentVolume
metadata:
        name: pvvol-1
spec:
        capacity:
                storage: 1Gi
        accessModes:
                - ReadWriteMany
        persistentVolumeReclaimPolicy: Recycle
        nfs:
                path: /home/joel/LF258/8-volumes/share
                server: k8scp
                readOnly: false
