apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
  creationTimestamp: "2022-07-12T19:23:27Z"
  generation: 1
  labels:
    controller-uid: 40ff550d-204d-44e0-aecb-7ee571784fbe
    job-name: sleepy
  name: sleepy
  namespace: default
  resourceVersion: "10940"
  uid: 40ff550d-204d-44e0-aecb-7ee571784fbe
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 40ff550d-204d-44e0-aecb-7ee571784fbe
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 40ff550d-204d-44e0-aecb-7ee571784fbe
        job-name: sleepy
    spec:
      containers:
      - args:
        - "3"
        command:
        - /bin/sleep
        image: busybox
        imagePullPolicy: Always
        name: resting
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2022-07-12T19:23:41Z"
  conditions:
  - lastProbeTime: "2022-07-12T19:23:41Z"
    lastTransitionTime: "2022-07-12T19:23:41Z"
    status: "True"
    type: Complete
  startTime: "2022-07-12T19:23:27Z"
  succeeded: 1
  uncountedTerminatedPods: {}
