apiVersion: v1
data:
  Corefile: ".:53 {\n    rewrite stop { \n      name regex (.*)\\.test\\.io {1}.default.svc.cluster.local\n
    \     answer name (.*)\\.default\\.svc\\.cluster\\.local {1}.test.io\n      }\n
    \   errors\n    health {\n       lameduck 5s\n    }\n    ready\n    kubernetes
    cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough
    in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n    forward
    . /etc/resolv.conf {\n       max_concurrent 1000\n    }\n    cache 30\n    loop\n
    \   reload\n    loadbalance\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-19T17:26:16Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "81367"
  uid: 3dcb2277-883b-48d8-a695-0d51727b345b
